# 随机数值小数位模板 如: 8.2
decimalFormat: "#.#"
compositeGui:
  guiInfo: "&c属性附魂台"
  clickInfo:
    name: '&6点此查看信息'
    lore:
    - '&7&m---------------------------------------------'
    - "&6装备类型为: &a{0} &7(仅允许相同类型的附魂材料)"
    - "&e装备品质为: &a{1}"
    - "&b拥有属性数: &a{2}"
    - "&9最大属性数: &a{3}"
    - "&e提升后品质: &a{4}"
    - "&e提升品质需要材料: &a{5}"
    - "&9提升后最大属性数: &a{6}"
    - '&7&m---------------------------------------------'
    - "&9每件附魂材料含有一条属性值！对应一种属性分类！"
    - "&9每件装备仅允许拥有两条属性分类一致的属性值！"
    - "&9在附魂过程中，如果附魂材料不符或者对应附魂材料属性多余"
    - "&9该附魂材料将不作处理，并发出提示！"
    - "&7&m---------------------------------------------"
  clickStartInfo:
    name: "&c&l点此开始附魂"
    lore:
    - "&6左边装备，&b右边提升材料，&a上边附魂材料"
    - "&7&m---------------------------------------------"
    - "&9每件附魂材料含有一条属性值！对应一种属性分类！"
    - "&9每件装备仅允许拥有两条属性分类一致的属性值！"
    - "&9在附魂过程中，如果附魂材料不符或者对应附魂材料属性多余"
    - "&9该附魂材料将不作处理，并发出提示！"
    - "&7&m---------------------------------------------"
suckingTableGui:
  guiInfo: "&c属性抽魂台"
  clickStartInfo:
    name: "&c&l点此开始抽魂"
    lore:
    - "&6左边装备，&b右边抽魂材料"
    - "&7&m---------------------------------------------"
    - "&9抽取成功后，装备的对应属性会减去！"
    - "&9同时你会获得一个附加了对应属性的附魂材料！"
    - "&7&m---------------------------------------------"
itemstack:
  growUp: "&a可培养"
  noGrowUp: "&8不可培养"
  maxQuality: "当前已是最高品质"
message:
  chou:
    noMEItem: "&c[&eMEquipment&c] &7不是可吸附属性的装备(左边)！"
    noAttribute: "&c[&eMEquipment&c] &7可吸附属性条数为零(左边)！"
    noXiFu: "&c[&eMEquipment&c] &7不是吸附材料(右边)！"
    noPlace: "&c[&eMEquipment&c] &7材料处(吸附材料)(右边)，或者装备处(左边)没有放物品！"
    success: "&c[&eMEquipment&c] &a抽取成功！属性: {0}"
    fail: "&c[&eMEquipment&c] &7抽取失败！"
  fu:
    noPlace: "&c[&eMEquipment&c] &7装备处(左边)没有放物品！"
    noMEItem: "&c[&eMEquipment&c] &7不是可附加属性的装备(左边)！"
    noGrowUp: "&c[&eMEquipment&c] &7不是可培养品质的装备(左边)！"
    noSjItem: "&c[&eMEquipment&c] &7材料处(属性材料)(右边)没有放物品！"
    sjItemError: "&c[&eMEquipment&c] &7材料错误！你需要放置 &a{0} &7个 {1} &7!"
    sjItemNum: "&c[&eMEquipment&c] &7材料数量不足！你还要多放 &a{0} &7个 {1} &7!"
    moreAttr: "&c[&eMEquipment&c] &7处于GUI界面 &b {0} &7位置的材料属性类型多余，该装备已经拥有了2条！"
    typeError: "&c[&eMEquipment&c] &7处于GUI界面 &b {0} &7位置的吸附材料类型和装备类型不符！"
    maxAttr: "&c[&eMEquipment&c] &7该装备品质允许的最大属性数已经满了，处于GUI界面 &b {0} &7位置的物品不作处理！"
    noXiFu: "&c[&eMEquipment&c] &7处于GUI界面 &b{0} &7位置的物品并非吸附属性材料！"
    up: "&c[&eMEquipment&c] &a你的装备品质提升到了 {0} &a!"
    add: "&c[&eMEquipment&c] &a你为装备附加了新属性 &c[{0}&c]&a！"
    qualityError: "&c[&eMEquipment&c] &4出错！请联系管理员检查quality.yml文件中id为 &f{0} &4的品质是否正确设定？id需从上往下连贯！"
    maxQuality: "&c[&eMEquipment&c] &e该装备已经是最高品质的装备了！"

